# Generated by Django 5.1.1 on 2024-09-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('score_home', models.IntegerField()),
                ('score_away', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('competition', models.CharField(max_length=100)),
            ],
        ),
    ]
