# Generated by Django 5.1.1 on 2024-09-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
