# Generated by Django 5.1.1 on 2024-09-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_to_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
