# Generated by Django 5.1.1 on 2024-09-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('technology', 'Technology'), ('politics', 'Politics')], default='sports', max_length=250),
        ),
    ]
